version: "3.9"

x-deploy: &default-deploy
  resources:
    limits:
      cpus: "1"
      memory: "2048MB"

x-service: &default-service
  image: in/flight:latest
  build:
    context: .
    dockerfile: ./devops/Dockerfile
    args:
      - REQUIREMENTS=all
  env_file:
    - .env.local

services:
  flight:
    << : *default-service
    depends_on:
      - flistack
      - flidog
    command: >
      bash -c "watchmedo auto-restart --pattern='*.py' --directory='/home/in-flight/app/' --recursive --
      celery -A app.celery worker --loglevel=INFO -E -Ofair --pidfile /tmp/celery.pid"
    networks:
      - ping-net
    volumes:
      - "./src:/home/in-flight/app:rw"
    deploy: *default-deploy
    labels:
      com.datadoghq.ad.logs: '[{"source": "in-flight", "service": "in-flight"}]'
      com.datadoghq.tags.env: "development"
      com.datadoghq.tags.version: "1.0.0"

  flipys:
    << : *default-service
    volumes:
      - "./src:/home/in-flight/app:rw"
      - "./requirements:/opt/requirements:rw"
      - "./scripts:/opt/scripts:ro"
      - "./pyproject.toml:/home/in-flight/pyproject.toml:ro"
      - "./mypy.ini:/home/in-flight/mypy.ini:ro"
    environment:
      - ENV_FILENAME=test.py
    profiles:
      - tests

  flistack:
    image: localstack/localstack:2.3.1-amd64
    environment:
      - SERVICES=sqs,s3
      - GATEWAY_LISTEN=0.0.0.0:4567
      - EAGER_SERVICE_LOADING=1
    volumes:
      - "./.aws:/etc/localstack/init/ready.d:ro"
      - "./.localstack:/var/lib/localstack:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - ping-net
      - service-grp-net
    deploy: *default-deploy

  flidog:
    image: datadog/agent:7.48.0-rc.9-jmx
    env_file:
      - .env.dd
    environment:
      - DD_LOGS_ENABLED=true
      - DD_SITE=datadoghq.com
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
    profiles:
      - dd-agent

networks:
  ping-net: {}
  service-grp-net:
    external: true
