version: "3.9"

x-deploy: &default-deploy
  resources:
    limits:
      cpus: "1"
      memory: "2048MB"

x-service: &default-service
  image: in/flight:latest
  build:
    context: .
    dockerfile: ./devops/Dockerfile
    args:
      - REQUIREMENTS=all
  env_file:
    - .env.local

services:
  flight:
    << : *default-service
    depends_on:
      - flistack
      - flidog
    command: >
      bash -c "watchmedo auto-restart --pattern='*.py' --directory='/home/in-flight/app/' --recursive --
      celery -A app.celery worker --loglevel=INFO -E -Ofair --pidfile /tmp/celery.pid"
    networks:
      - ping-net
    volumes:
      - ./src:/home/in-flight/app:rw
    deploy: *default-deploy
    labels:
      com.datadoghq.ad.logs: '[{"source": "in-flight", "service": "in-flight"}]'
      com.datadoghq.tags.env: "dev"
      com.datadoghq.tags.version: "1.0.0"

  flipys:
    << : *default-service
    volumes:
      - ./src:/home/in-flight/app:rw
      - ./requirements:/opt/requirements:rw
      - ./scripts:/opt/scripts:ro
      - ./pyproject.toml:/home/in-flight/pyproject.toml:ro
      - ./mypy.ini:/home/in-flight/mypy.ini:ro
    environment:
      - ENV_FILENAME=test.py
    profiles:
      - tests

  flistack:
    image: localstack/localstack:2.1.0-amd64
    environment:
      - SERVICES=sqs,s3
      - GATEWAY_LISTEN=0.0.0.0:4567
      - EAGER_SERVICE_LOADING=1
    volumes:
      - "./.aws:/etc/localstack/init/ready.d"
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ping-net
      - service-grp-net
    deploy: *default-deploy

  flidog:
    image: gcr.io/datadoghq/agent:7
    environment:
      - DD_API_KEY=<>
      - DD_LOGS_ENABLED=true
      - DD_SITE=datadoghq.com
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"

networks:
  ping-net: {}
  service-grp-net:
    external: true
