[tool.black]
line-length = 100
target-version = ['py311']
exclude = '''
(
  /(
      \.eggs # exclude a few common directories in the
    | \.git  # root of the project
    | \.venv
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100

[tool.pytest.ini_options]
minversion = 7.2
addopts = "-x --durations=5 -n 2"
testpaths = ["tests"]
python_files = "test_*"
required_plugins = "pytest-celery"
cache_dir = "/home/pingook/.pytest_cache"
